version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: imageflow-backend
    ports:
      - "8686:8686"
    volumes:
      - ./static/images:/app/static/images
      - ./config:/app/config
      - ./.env:/app/.env:ro
    environment:
      - API_KEY=${API_KEY:-default_api_key}
      - STORAGE_TYPE=${STORAGE_TYPE:-local}
      - LOCAL_STORAGE_PATH=/app/static/images
      - S3_ENDPOINT=${S3_ENDPOINT:-}
      - S3_REGION=${S3_REGION:-}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY:-}
      - S3_SECRET_KEY=${S3_SECRET_KEY:-}
      - S3_BUCKET=${S3_BUCKET:-}
      - CUSTOM_DOMAIN=${CUSTOM_DOMAIN:-}
      - MAX_UPLOAD_COUNT=${MAX_UPLOAD_COUNT:-20}
      - IMAGE_QUALITY=${IMAGE_QUALITY:-80}
      - WORKER_THREADS=${WORKER_THREADS:-4}
      - COMPRESSION_EFFORT=${COMPRESSION_EFFORT:-6}
      - FORCE_LOSSLESS=${FORCE_LOSSLESS:-false}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8686/", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - imageflow-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: imageflow-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./.env:/.env:ro
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://backend:8686}
      - NEXT_PUBLIC_REMOTE_PATTERNS=${NEXT_PUBLIC_REMOTE_PATTERNS:-}
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - imageflow-network

networks:
  imageflow-network:
    driver: bridge
